import { Suspense } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { FileText, Loader2 } from 'lucide-react'
import { QuotationsList } from '@/components/dashboard/quotations-list'
import { getAllQuotationsWithDetails } from '@/lib/services/quotationService'

export const dynamic = 'force-dynamic'

export default async function AdminQuotationsPage() {
    return (
        <div className="p-4 sm:p-6 lg:p-8 max-w-7xl mx-auto space-y-6">
            {/* Header */}
            <div>
                <h1 className="text-xl md:text-2xl font-bold text-gray-900">Quotations Ledger</h1>
                <p className="text-xs md:text-sm text-gray-500 mt-1">
                    Manage, review, and convert customer quotations generated by field agents
                </p>
            </div>

            {/* Quotations List Card */}
            <Card>
                <CardHeader>
                    <CardTitle className="text-lg flex items-center gap-2">
                        <FileText className="h-5 w-5 text-primary" />
                        All Quotations
                    </CardTitle>
                </CardHeader>
                <CardContent>
                    <Suspense fallback={
                        <div className="flex flex-col items-center justify-center py-12 gap-3">
                            <Loader2 className="h-8 w-8 text-primary animate-spin" />
                            <p className="text-sm text-gray-500">Loading quotations...</p>
                        </div>
                    }>
                        <QuotationsLoader />
                    </Suspense>
                </CardContent>
            </Card>
        </div>
    )
}

async function QuotationsLoader() {
    const quotations = await getAllQuotationsWithDetails()
    return <QuotationsList quotations={quotations} />
}
