'use client'

import { useState, useEffect } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { FileText, Loader2 } from 'lucide-react'
import { QuotationsList } from '@/components/dashboard/quotations-list'
import { createClient } from '@/lib/supabase/client'
import type { QuotationWithDetails } from '@/lib/services/quotationService'

export default function AdminQuotationsPage() {
    const [quotations, setQuotations] = useState<QuotationWithDetails[]>([])
    const [loading, setLoading] = useState(true)

    useEffect(() => {
        async function loadQuotations() {
            try {
                const supabase = createClient()
                const { data, error } = await supabase
                    .from('quotations')
                    .select(`
                        *,
                        client:clients(*),
                        created_by_user:app_users!quotations_created_by_fkey(*)
                    `)
                    .order('created_at', { ascending: false })

                if (error) {
                    console.error('Error fetching quotations:', error)
                } else {
                    setQuotations((data || []) as QuotationWithDetails[])
                }
            } catch (err) {
                console.error('Failed to load quotations:', err)
            } finally {
                setLoading(false)
            }
        }

        loadQuotations()
    }, [])

    return (
        <div className="p-4 sm:p-6 lg:p-8 max-w-7xl mx-auto space-y-6">
            {/* Header */}
            <div>
                <h1 className="text-xl md:text-2xl font-bold text-gray-900">Quotations Ledger</h1>
                <p className="text-xs md:text-sm text-gray-500 mt-1">
                    Manage, review, and convert customer quotations generated by field agents
                </p>
            </div>

            {/* Quotations List Card */}
            <Card>
                <CardHeader>
                    <CardTitle className="text-lg flex items-center gap-2">
                        <FileText className="h-5 w-5 text-primary" />
                        All Quotations
                    </CardTitle>
                </CardHeader>
                <CardContent>
                    {loading ? (
                        <div className="flex flex-col items-center justify-center py-12 gap-3">
                            <Loader2 className="h-8 w-8 text-primary animate-spin" />
                            <p className="text-sm text-gray-500">Loading quotations...</p>
                        </div>
                    ) : (
                        <QuotationsList quotations={quotations} />
                    )}
                </CardContent>
            </Card>
        </div>
    )
}
