import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { FileText } from 'lucide-react'
import { QuotationsList } from '@/components/dashboard/quotations-list'
import { createClient } from '@/lib/supabase/server'
import type { QuotationWithDetails } from '@/lib/services/quotationService'

export const dynamic = 'force-dynamic'

export default async function AdminQuotationsPage() {
    const supabase = await createClient()
    const { data, error } = await supabase
        .from('quotations')
        .select(`
            *,
            client:clients(*),
            created_by_user:app_users!quotations_created_by_fkey(*)
        `)
        .order('created_at', { ascending: false })

    if (error) {
        console.error('Error fetching quotations:', error)
    }

    const quotations = (data || []) as QuotationWithDetails[]

    return (
        <div className="p-4 sm:p-6 lg:p-8 max-w-7xl mx-auto space-y-6">
            {/* Header */}
            <div>
                <h1 className="text-xl md:text-2xl font-bold text-gray-900">Quotations Ledger</h1>
                <p className="text-xs md:text-sm text-gray-500 mt-1">
                    Manage, review, and convert customer quotations generated by field agents
                </p>
            </div>

            {/* Quotations List Card */}
            <Card>
                <CardHeader>
                    <CardTitle className="text-lg flex items-center gap-2">
                        <FileText className="h-5 w-5 text-primary" />
                        All Quotations
                    </CardTitle>
                </CardHeader>
                <CardContent>
                    <QuotationsList quotations={quotations} />
                </CardContent>
            </Card>
        </div>
    )
}
